// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file joint_6dof.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _JOINT_6DOF_H_
#define _JOINT_6DOF_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(joint_6dof_SOURCE)
#define joint_6dof_DllAPI __declspec( dllexport )
#else
#define joint_6dof_DllAPI __declspec( dllimport )
#endif // joint_6dof_SOURCE
#else
#define joint_6dof_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define joint_6dof_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure joint_6dof defined by the user in the IDL file.
 * @ingroup JOINT_6DOF
 */
class joint_6dof
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport joint_6dof();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~joint_6dof();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object joint_6dof that will be copied.
     */
    eProsima_user_DllExport joint_6dof(
            const joint_6dof& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object joint_6dof that will be copied.
     */
    eProsima_user_DllExport joint_6dof(
            joint_6dof&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object joint_6dof that will be copied.
     */
    eProsima_user_DllExport joint_6dof& operator =(
            const joint_6dof& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object joint_6dof that will be copied.
     */
    eProsima_user_DllExport joint_6dof& operator =(
            joint_6dof&& x);

    /*!
     * @brief This function copies the value in member joint_name
     * @param _joint_name New value to be copied in member joint_name
     */
    eProsima_user_DllExport void joint_name(
            const std::string& _joint_name);

    /*!
     * @brief This function moves the value in member joint_name
     * @param _joint_name New value to be moved in member joint_name
     */
    eProsima_user_DllExport void joint_name(
            std::string&& _joint_name);

    /*!
     * @brief This function returns a constant reference to member joint_name
     * @return Constant reference to member joint_name
     */
    eProsima_user_DllExport const std::string& joint_name() const;

    /*!
     * @brief This function returns a reference to member joint_name
     * @return Reference to member joint_name
     */
    eProsima_user_DllExport std::string& joint_name();
    /*!
     * @brief This function copies the value in member joint_pos
     * @param _joint_pos New value to be copied in member joint_pos
     */
    eProsima_user_DllExport void joint_pos(
            const std::array<double, 6>& _joint_pos);

    /*!
     * @brief This function moves the value in member joint_pos
     * @param _joint_pos New value to be moved in member joint_pos
     */
    eProsima_user_DllExport void joint_pos(
            std::array<double, 6>&& _joint_pos);

    /*!
     * @brief This function returns a constant reference to member joint_pos
     * @return Constant reference to member joint_pos
     */
    eProsima_user_DllExport const std::array<double, 6>& joint_pos() const;

    /*!
     * @brief This function returns a reference to member joint_pos
     * @return Reference to member joint_pos
     */
    eProsima_user_DllExport std::array<double, 6>& joint_pos();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const joint_6dof& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    std::string m_joint_name;
    std::array<double, 6> m_joint_pos;
};

#endif // _JOINT_6DOF_H_